apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secrets
type: Opaque
data:
  REMOTE_MONOGO_CONNECTION_STRING: bW9uZ28tbW9uZ29kYi0wLm1vbmdvLW1vbmdvZGItaGVhZGxlc3MubW9uZ28uc3ZjLmNsdXN0ZXIubG9jYWwsbW9uZ28tbW9uZ29kYi0xLm1vbmdvLW1vbmdvZGItaGVhZGxlc3MubW9uZ28uc3ZjLmNsdXN0ZXIubG9jYWwK
  LOCAL_MONOGO_CONNECTION_STRING: bW9uZ28tbW9uZ29kYi0wLm1vbmdvLW1vbmdvZGItaGVhZGxlc3MubW9uZ28uc3ZjLmNsdXN0ZXIubG9jYWwsbW9uZ28tbW9uZ29kYi0xLm1vbmdvLW1vbmdvZGItaGVhZGxlc3MubW9uZ28uc3ZjLmNsdXN0ZXIubG9jYWwK